<!--====================  footer area ====================-->
<div class="footer-area-wrapper reveal-footer bg-gray">
    
    <div class="footer-copyright-area section-space--pb_30 mt-20">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-6 text-center text-md-start">
                    <span class="copyright-text">&copy; 2026 Rialto Insights. All Rights Reserved.</span>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <ul class="list ht-social-networks solid-rounded-icon">

                        <li class="item">
                            <a href="https://facebook.com" target="_blank" aria-label="Facebook" class="social-link hint--bounce hint--top hint--primary">
                                <i class="fab fa-facebook-f link-icon"></i>
                            </a>
                        </li>
                        <li class="item">
                            <a href="https://linkedin.com" target="_blank" aria-label="Linkedin" class="social-link hint--bounce hint--top hint--primary">
                                <i class="fab fa-linkedin link-icon"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--====================  End of footer area  ====================-->